### ISSUE TITLE
GammaOS

### ISSUE THREAD

**Issue by Bakemon00** [TheGammaSqueeze/GammaOS#102]
Boa tarde obrigado pelo trabalho impecável, 
Eu estava realizando a instalação do GammaOS no meu RG505 que chegou ontem e no processo final onde aparece que ira apagar os arquivos e pode-se clicar ctrl+c para parar, acabou a energia da minha casa e agora o meu aparelho so ficavibrando e reiniciando com essa mensagem na tela:
info:lock flag is: unlock!!
Poderia me auxiliar por gentileza, estou desesperado, não sei o que fazer e o aparelho nao sai disso de forma alguma.

**Comment by Bakemon00** [comment]
sorry
Good afternoon, thank you for the impeccable work,
I was installing GammaOS on my RG505 that arrived yesterday and in the final process where it appears that it will delete the files and you can click ctrl+c to stop, the power went out in my house and now my device just keeps vibrating and restarting with this message on the screen:
info:lock flag is: unlock!!
Could you please help me, I'm desperate, I don't know what to do and the device won't get rid of it in any way.

**Comment by DarkN-83** [comment]
https://github.com/TheGammaSqueeze/GammaOS#help-my-device-is-no-longer-booting-or-i-want-to-go-back-to-stock-os
