### ISSUE TITLE
Cannot continue without a "proper" internet connection

### ISSUE THREAD

**Issue by timothyparez** [TheGammaSqueeze/GammaOS#104]
After installing GamaOS on the RG405M I can connect to my wifi,
but because of my internet provider I am unable to connect to some services.  

As a result I am stuck on the Connect to Wi-Fi screen which tells me I  
have a limited connection. If only I could skip this screen then I'd be able to
configure the connection at a later time.

**Comment by sammcj** [comment]
GammaOS install a third party DNS provider, have you tried disabling it?

I had to do that to make it work on my network.

**Comment by TheGammaSqueeze** [comment]
https://github.com/TheGammaSqueeze/GammaOS/issues/142#issuecomment-1961179789
