### ISSUE TITLE
Psp Games not working

### ISSUE THREAD

**Issue by bmakhale** [TheGammaSqueeze/GammaOS#105]
I have 250 PSP games on my 505 and they will not work using multiple emulators. My Saturn games will not either, but I saw that the next update will resolve that.

**Comment by Jonasbeavis** [comment]
Are you trying to use CHD files? If so , only PPSSPP dev builds run those , and by experience doesn't run well. Use CSO or ISO only with PS store PPSSPP emulator.

**Comment by JamesRHarris** [comment]
On my 505 I had to change the render from vulkan to gl to get PSP working. I noticed that I needed to manually save the config in retroarch to get it to stick.

**Comment by SqueakyRafiki** [comment]
Where did you see that the next update will resolve Saturn issues?
 Both the RetroArch cores and the Yaba Sanshiro 2 app is having trouble running Grandia.
