### ISSUE TITLE
I'm booting back into stock firmware and not GammaOS.

### ISSUE THREAD

**Issue by CraftRaid** [TheGammaSqueeze/GammaOS#120]
I'm booting back into stock firmware and not GammaOS. I already tried the method "https://github.com/TheGammaSqueeze/GammaOS#help-my-device-is-no-longer-booting-or-i-want-to-go-back-to-stock-os" , and installed Stock OS v1.15. After that, I tried to install Gamma OS again, and my RG405m only starts on the stock firmware.
I have already tried doing all these procedures 3 times. Currently the RG405m is unlocked and has stock rom v1.15.

**_What do I need to do to be able to install Gamma OS?_**

Thanks a lot for the help.

**Comment by TheGammaSqueeze** [comment]
Check your ADB install, ensure you follow the instructions closely to ensure adb tools are in your path and make sure that you are using the correct fastboot.exe.
