### ISSUE TITLE
Waking up the RG405m takes 2 seconds?

### ISSUE THREAD

**Issue by LinkTree3** [TheGammaSqueeze/GammaOS#125]
After installing Gamma OS I noticed that when waking up the device using the dedicated on/off button it takes 2 seconds before I see anything on the screen. It wasn't like that on stock OS

Is there something that can be done to speed it up so the experience feels more seamless?

**Comment by TheGammaSqueeze** [comment]
This is normal behaviour, GammaOS actually helps the device reach a very deep sleep, thus saving battery on standby. No plans to change this.
