### ISSUE TITLE
Don't use run as administrator during upgrade

### ISSUE THREAD

**Issue by jeroendewaal** [TheGammaSqueeze/GammaOS#136]
Hi,

I did the upgrade to 1.5.1 on my RG505. The update went really fast. Even that fast that I was going to question the success.
I could nowhere find the installed version. In the changelog i've read that Firefox was added. On my RG505 I didn't see Firefox, so now i knew that the upgrade failed.
From different other programs i'm used to run a .bat file of .exe file as administrator. I've discovered that running the FlashPartitions script with the submenu "run as administrator" won't upgrade the RG505.
When I just double clicked the script it runs perfect.
So a little sidenote with "don't run as administrator" will probably help others?
Sorry for my bad English, I hope you understand.

Kind regards,

Jeroen. (The Netherlands)

**Comment by TheGammaSqueeze** [comment]
Noted, thanks for letting me know.
