### ISSUE TITLE
Problem with the tool to debrick RG505 (sorry, Google translator)

### ISSUE THREAD

**Issue by EduVieiraF** [TheGammaSqueeze/GammaOS#140]
I installed the Gama OS system, but the console didn't want to start after some gaming. I tried the recovery method provided in the thread here, but I encounter this error: Failed(UB1142) Wait input time out
![31e2b52c-98bf-4459-ae46-94905e89703d](https://github.com/TheGammaSqueeze/GammaOS/assets/159670736/783cb0b0-e6f9-426b-a6db-62ecc6fb4e48)

**Comment by TheGammaSqueeze** [comment]
Try different USB cable and different USB port.

**Comment by reyisidroo** [comment]
Hi, I have the same problem.

I have tried on three different computers with several different USB Type-C cables and I always get the same error on FDL2.

Could anyone help me?
