### ISSUE TITLE
Change default frontend

### ISSUE THREAD

**Issue by AndreaCCIE** [TheGammaSqueeze/GammaOS#149]
I've configured EmulationStation as the default frontend, following this guide:
https://www.youtube.com/watch?v=qGqOSvh2UjQ

Everything works fine, but when I reboot the handheld, Daijisho is set as the default frontend again.
Is there a way to prevent this behaviour?

**Comment by purelygrey** [comment]
I know this is old, but how did you do it? I tried seemingly everything and Daijisho still pops up after reboot even if I delete it. Not an expert on Android, kind of out of ideas here. Wouldn't hurt to add this to the README as well

EDIT: Nevermind, I suppose it didn't get deleted properly the first time. For anyone who stumbles across this issue -- just delete Daijisho by using something like UninstallSystemApps and you should be okay
