### ISSUE TITLE
RG505 glitchy when first booted

### ISSUE THREAD

**Issue by tye595** [TheGammaSqueeze/GammaOS#152]
I can't find much info on if anyone else has ran into this one.

I recently installed GammaOS on my RG505. Works great, but when I need to turn it off or reboot...turning it back on isn't normal.

When it first boots up, the power menu opens itself up and doesn't work. The main screen doesn't respond and navigation is near impossible. 

Eventually, it'll pop up a prompt stating the system UI has crashed. I tap the option to close the app, which promptly reloads the system UI and becomes fully functional and everything works flawlessly. Usually after 2 to 5 minutes.

So this one has me pretty confused. Otherwise really like GammaOS on this device.

**Comment by TheGammaSqueeze** [comment]
You can resolve this by doing a factory reset within the recovery menu or from within the Android settings.

Otherwise, flash the stock firmware again, then follow the GammaOS install guide again.
