### ISSUE TITLE
There is no EraseUserData.bat file in the folder

### ISSUE THREAD

**Issue by andygreen6** [TheGammaSqueeze/GammaOS#160]
Do you have a direct file download for this?
Thanks in advance.

**Comment by dfreivald** [comment]
Is there a file named "EraseUserData" ?

**Comment by andygreen6** [comment]
EraseUserData.sh only. No EraseUserData.bat file. Im using windows btw.

**Comment by dfreivald** [comment]
Make sure "Hide extensions for known file types" is unchecked.
If you really don't have it, make sure your antivirus isn't deleting it.

**Comment by andygreen6** [comment]
Thanks for the tip!
I tried to redownload your updated file and it worked.

**Comment by dfreivald** [comment]
Awesome, although all the credit goes to @TheGammaSqueeze 

This is a common issue, so here's the contents of the file in case others also need it.

```
@echo off
echo Ignore any errors.
echo.
fastboot erase metadata
fastboot format metadata
fastboot erase cache
fastboot format cache
fastboot erase userdata
fastboot format userdata
fastboot -w



echo.
echo Ignore any errors. /userdata and /metadata wiped. Factory reset complete. Closing this window in 60 seconds.
timeout /t 60

```

**Comment by andygreen6** [comment]
Thanks again for the help. And ofcourse, many thanks  @TheGammaSqueeze
<https://github.com/TheGammaSqueeze>!!
