### ISSUE TITLE
Anbernic RG505

### ISSUE THREAD

**Issue by DiogoR10** [TheGammaSqueeze/GammaOS#162]
Boa tarde! Alguém poderia me ajuda aonde consigo os 13 arquivos para eu restaurar o meu anbernic modo padrão do anbernic RG 505

**Comment by dfreivald** [comment]
It's not13 files, it's a single package for the RG505. https://drive.google.com/file/d/1WNildo8TZDW6L4tzY9SDEjL3NhPGg_gG/view
