### ISSUE TITLE
Can’t install/link accounts to Facebook

### ISSUE THREAD

**Issue by HartR** [TheGammaSqueeze/GammaOS#163]
Hey there, id like to be able to link games to my Facebook account for cloud save purposes. However when i try to download Facebook from Google play i just get a blank screen when opening it. 

On a possibly related note, I’ve noticed this software probably has a built in Adblock? Could that be the issue that it’s blocking Facebook urls? If so, how do i disable the Adblock?

thank you

**Comment by TheGammaSqueeze** [comment]
Try disabling private DNS within the networking settings. That will unblock ads.

**Comment by HartR** [comment]
> Try disabling private DNS within the networking settings. That will unblock ads.

That worked! Thank you
