### ISSUE TITLE
gammaOS 1.5.1 no USB-C to HDMI kernel driver

### ISSUE THREAD

**Issue by warohs** [TheGammaSqueeze/GammaOS#168]
Please add the kernel drivers for mhl/USB-C to HDMI. The hardware has the ability but the kernel modules are missing. Or I'm not good at this. Other devices work fine, including a small dock I bought for my rg505, even the Ethernet one I tried. But the mhl is missing kernel support. 
Otherwise, top shelf os!
Bad instructions found only for installing over Linux, but I got there. Thank you

**Comment by TheGammaSqueeze** [comment]
We do not have kernel sources.
