### ISSUE TITLE
Unable to flash

### ISSUE THREAD

**Issue by nhhrky** [TheGammaSqueeze/GammaOS#186]
When following the protocol to revert back to stock OS, I am unable to long-press BACK + VOLUME DOWN + POWER without the device turning off. Can someone please advise?

**Comment by Kamins2017** [comment]
When you say you’re pressing “back”, you’re pressing the home button yes? I was doing the same thing lol. It’s the home button, volume down and power.

**Comment by nhhrky** [comment]
A good thought, but I am indeed pressing the home button.

**Comment by Kamins2017** [comment]
This worked for me. I hope it works for you!

https://www.youtube.com/watch?v=fT6kulEfWXo
