### ISSUE TITLE
bricked rg556

### ISSUE THREAD

**Issue by david7919** [TheGammaSqueeze/GammaOS#204]
I managed to compile a working twrp with hovatec twrp builder and flashed it to the vendor_boot_a partition. 
twrp and everything else kept working until I flashed an empty vbmeta (trying to disable avb) through twrp and rebooted the system. 
Since then I'm stuck on first boot screen with the bootloader unlocked message.

I tried getting in recovery mode in order to reflash firmware in twrp, or reset or reflash firmware in fastboot mode.
Unfortunately power + volume up or down or both didnt do anything.

Do you know if there are different button combinations (like power + start for example) for accessing recovery, fastboot, bootloader?

I will try your unbricker/spdflashtool as soon as I get my hands on a windows pc since I only have a linux machine.

**Comment by Senna1171** [comment]
Hey how did you manage to get it working? I broke mine doing the flash for the control sticks, the boot unlocker must have messed up or something. Cant use the researchdownload to flash my device with the RG556 unbricker pac either.
