### ISSUE TITLE
"Select" and "Start" cannot be used to quit RetroArch.

### ISSUE THREAD

**Issue by DieHardMan5x** [TheGammaSqueeze/GammaOS#26]
"Select" and "Start" cannot be used to quit RetroArch. Even with Xbox Mode disabled it does not work. Other hotkeys together with "Select" work strangely enough. 
I have tried all the settings but nothing has helped. "Confirm quit" is enabled.

It works on the stock firmware however.

![Screenshot_20230701-014702_RetroArch (AArch64)](https://github.com/TheGammaSqueeze/GammaOS/assets/74651322/ec3465e2-c901-46fa-a80a-dffcfcdd3b25)
![Screenshot_20230701-014533_RetroArch (AArch64)](https://github.com/TheGammaSqueeze/GammaOS/assets/74651322/47643c7e-c105-404b-87e1-343c849a7618)
![Screenshot_20230701-014643_RetroArch (AArch64)](https://github.com/TheGammaSqueeze/GammaOS/assets/74651322/3f2fb6b1-79d6-4373-ac7d-114ec1a75ac3)
![Screenshot_20230701-014554_RetroArch (AArch64)](https://github.com/TheGammaSqueeze/GammaOS/assets/74651322/6d5ad965-400c-4e22-b6ac-cadc4a73bb9e)

Sometimes shortly after starting a rom I get the correct confirm message to appear.

![Screenshot_20230701-015230_RetroArch (AArch64)](https://github.com/TheGammaSqueeze/GammaOS/assets/74651322/cdc5a900-b047-4b45-a8f2-6ac46ae7e625)

**Comment by eduardopatricio** [comment]
I believe your problem might be your current Retroarch settings. I see you
have "Hotkey enable" set to the 'select' key (109). That means all your
hotkeys will be combos by default ("select" + "some-other-key").
On top of that, you have the "quit controller combo". So, you're mapping
"select" to 2 different things.

If you use select as a hotkey enabler for other things, I'd keep "select"
as "hotkey enabler", remove the "quit (controller combo)" option and set
the "start" key as "Quit".
In any case, even with your current problematic double mapping, pressing
select and start precisely together simultaneously should work to quit the
game. (I've double checked your configuration on my device here).

I hope this helps.
Cheers,
E.


*Eduardo Patricio, PhD*

Sound Designer / Lecturer at Bydgoszcz Music Academy
https://linktr.ee/eduardopatricio

**Comment by DieHardMan5x** [comment]
Thanks for the help, if I use "Start" as a hotkey for "Quit" then everything works fine. There my memory played a trick on me, the issue can be closed.
