### ISSUE TITLE
Unable to install DraStic from Play Store

### ISSUE THREAD

**Issue by skinlab** [TheGammaSqueeze/GammaOS#3]
Trying to install DraStic Nintendo DS emulator purchased from the Play Store and after downloading it gives error "Can't install DraStic DS Emulator. Try again..."

**Comment by TheGammaSqueeze** [comment]
You may need to do a factory reset.

Just do a factory reset by holding power button, go to restart, then go to recovery.

From recovery menu, choose the factory reset option. Use the volume keys to navigate the menu, and the power button to confirm selection.
