### ISSUE TITLE
Bluetooth gamepad Emulation for other devices or Android in general

### ISSUE THREAD

**Issue by svensvond** [TheGammaSqueeze/GammaOS#31]
Is it possible to port this to an "App" that we could use this feature on other roms for other devices?
Would love to get USB Controller like the razer kishi to work as a bt device.

**Comment by TheGammaSqueeze** [comment]
Hi, the code for my fix is here: https://github.com/TheGammaSqueeze/retrogame_joypad_2_xbox
It should be modifiable to work with other devices.
