### ISSUE TITLE
Battery drain after installing gamma os on RG405M

### ISSUE THREAD

**Issue by arongkatz** [TheGammaSqueeze/GammaOS#32]
Hello

First of all thank you for your work doing this great os, i know this might not be the space to comment this but wanted to say it anyways, youre making a cool gadget a lot better fun gadget!.

Now, since i installed the os, ive been getting huge battery drains, first when i played some old systems like nes or gba the battery percent would go from 90% to 80% in a matter of minutes not even an hour playing. I changed the power profile to Power saving mode and still getting this battery life

I managed to charged it full 3 or 4 days ago and today it was at 1%. Could i be missing something? do i need to adjust some settings?

**Comment by TheGammaSqueeze** [comment]
Hi, this might be down to calibration of the battery, the calibration data is lost when the bootloader is unlocked.

You'll need to let it drain completely, to the point of where the screen stops turning on and doesn't boot. 
From there, plug in the charger, turn the device on, then let it charge fully to 100% for a few hours. Let me know if this helps, thanks.

**Comment by arongkatz** [comment]
> Hi, this might be down to calibration of the battery, the calibration data is lost when the bootloader is unlocked.
> 
> You'll need to let it drain completely, to the point of where the screen stops turning on and doesn't boot. From there, plug in the charger, turn the device on, then let it charge fully to 100% for a few hours. Let me know if this helps, thanks.

Oh thanks, let me do that and come back to you with results

**Comment by ShalokShalom** [comment]
Did this help?

**Comment by ShalokShalom** [comment]
Did this help?

**Comment by lucasgomeshora222** [comment]
I have the same question

**Comment by inteyes** [comment]
This happened to me after unlocking the device. This method definitely helped restore the normal battery charge cycle. For me at least.

**Comment by TheGammaSqueeze** [comment]
Closing as resolved for now

**Comment by arongkatz** [comment]
So today i tried Max performance mode with a 100% battery. Played for maybe 5 minutes Starfox Assault on gamecube and now im on 73% battery life left. Is this expected?

**Comment by arongkatz** [comment]
Thanks will get to 0% and unplug the battery and come back with results
