### ISSUE TITLE
switch to gamma os full to the gamma os lite

### ISSUE THREAD

**Issue by mattitotti** [TheGammaSqueeze/GammaOS#34]
Hello i buy the RG 505 right now on my local market with the full gamma os installed if i wanna pass to gamma os lite  with no Google services what i must do? 
I Will give a donation for this project when the RG 505 Will arrive to me

**Comment by ale296** [comment]
Same as when upgrading the gammaOS to a newer version (check under the instruction). 
You must run the EraseUserData.bat script after you flashed the new version.
