### ISSUE TITLE
Navigation bars showing on some standalone emulators

### ISSUE THREAD

**Issue by arongkatz** [TheGammaSqueeze/GammaOS#35]
This may be more of a tech question than an issue but this didnt happen on stock os so i didnt know how to configure it. Im basically playing on yaba sanshiro and the nav bars just wont go away. Is there a way to remove them or do i need to go full tv mode?

Tv mode on yaba dont eben remove the bars:S

**Comment by dfreivald** [comment]
Had the same issue. It's hiding somewhere in the settings. It should be in both the pro/non-pro versions.

**Comment by TheGammaSqueeze** [comment]
Is there an option in Settings > Graphics for Hide Status bar and Navigation bar?

It is mentioned here in the developers site:
https://www.uoyabause.org/static_pages/guide

![image](https://github.com/TheGammaSqueeze/GammaOS/assets/116582950/2c31aaae-74ae-4e76-b6d0-1dae86b3ad89)

**Comment by arongkatz** [comment]
I disabled the navigation hint option but the line is still appearing on all apps and retroarch. I read somewhere this might be a bug on lineage?

**Comment by dfreivald** [comment]
I used the "Hide Status bar and Navigation bar" setting and that worked for me.
