### ISSUE TITLE
Feature Request: Performance Mode Switcher and Button Layout Switcher

### ISSUE THREAD

**Issue by anup-khanal** [TheGammaSqueeze/GammaOS#41]
XBOX and NS button layout switcher button and Performance mode switcher button on the quick settings bar when you swipe down would be nice to have.

**Comment by arongkatz** [comment]
This!

**Comment by dfreivald** [comment]
this is for future Gamma: https://developer.android.com/develop/ui/views/quicksettings-tiles

**Comment by jl-casella** [comment]
Hi guys, first of all, thanks for the GammaOS. Having said that, as a user and dev I also faced this issue, so I worked on an app to improve this experience.

I am releasing it today. So I was first letting you know here, before posting on some other forums.

You could take a look at it on Google Play. It already ships Button Layout Switcher in tiles. I will integrate soon the one for perf modes too. You can also add a Tile to quickly access the app, where you can tweak a lot of other device stuff.

The inspiration is a mix of CPU-Z. and the Settings app from the new AYA Neo Pocket AIR. For the Tiles, my next goal is to copy as much as possible the UI of the ones from Odin 2.

Once installed, the app will ask you for some permissions. Once you grant them all, disable notifications from the Magisk app, so you do not get a notification each time it uses `su` access:

![cap7](https://github.com/TheGammaSqueeze/GammaOS/assets/23145933/b531dd99-97e0-434d-b971-e9f8f147f8d6)

Google Play link: https://play.google.com/store/apps/details?id=com.controlcenter.android
