### ISSUE TITLE
Error when running the EraseUserData batch file - Anbernic RG505 installation

### ISSUE THREAD

**Issue by johnkottis** [TheGammaSqueeze/GammaOS#44]
Note: I try to install it using Win10 on parallels

Log:

Ignore any errors. This step can take up to 10 minutes, please wait!

fastboot: error: cannot load 'flash/userdata.img': No such file or directory
******** Did you mean to fastboot format this ext4 partition?
Erasing 'metadata'                                 OKAY [  0.153s]
Finished. Total time: 0.185s
CreateProcess failed: The system cannot find the file specified. (2)
fastboot: error: Cannot generate image for metadata
Erasing 'userdata'                                 OKAY [199.343s]
CreateProcess failed: The system cannot find the file specified. (2)
fastboot: error: Cannot generate image for userdata

Ignore any errors. /userdata and /metadata wiped. Factory reset complete. Closing this window in 60 seconds.

**Comment by TheGammaSqueeze** [comment]
This is expected behaviour.
