### ISSUE TITLE
RG505 randomly restarts or turn off when idle 

### ISSUE THREAD

**Issue by combo123** [TheGammaSqueeze/GammaOS#55]
The RG505 randomly restarts or completely turns off when the device is in idle. If it turns off, it flashes the Gamma Os logo and then completely shuts off, after that it is impossible to turn it back on (no reaction from any buttons, does not even charge), the only way is to phisically open the back and remove/reinstall the battery.

**Comment by TheGammaSqueeze** [comment]
Hi, you can force a reboot without disconnecting the battery by holding down volume and power button.

If the issue persists, I recommend reinstalling the stock firmware again, then install GammaOS again.

**Comment by combo123** [comment]
> 

Yes, also not reacting to that combination. Will try your second recomendation this week, will report back how it goes, thank you

**Comment by combo123** [comment]
> Hi, you can force a reboot without disconnecting the battery by holding down volume and power button.
> 
> If the issue persists, I recommend reinstalling the stock firmware again, then install GammaOS again.

Small update, I left the device to charge overnight (while it was turned off). So far the problem has not came back, has not turned off once, if anything new I will report back again :)

**Comment by AGvin** [comment]
Hi here!
Looks faced with same issue but for RG405M
On idle or sleep system restarted.

Already tried to fix this with restoring stock OS, and than again install GammaOS, but issue still reproduced.
It looks caused with some trim onTrimMemory service

![Screenshot_20230805-110920_Daijishō](https://github.com/TheGammaSqueeze/GammaOS/assets/743799/0d9e551d-b209-4d30-935e-c1a35ead1e02)

**Comment by combo123** [comment]
> Hi here! Looks faced with same issue but for RG405M On idle or sleep system restarted.
> 
> Already tried to fix this with restoring stock OS, and than again install GammaOS, but issue still reproduced. It looks caused with some trim onTrimMemory service
> 
> ![Screenshot_20230805-110920_Daijishō](https://user-images.githubusercontent.com/743799/258572226-0d9e551d-b209-4d30-935e-c1a35ead1e02.png)

Could you try turning it off and leaving it overnight to charge? That actually worked for me, so far so good

**Comment by AGvin** [comment]
> Could you try turning it off and leaving it overnight to charge? That actually worked for me, so far so  

Tried to do that, but it doesn't help

**Comment by BadgerB01** [comment]
I can also confirm, brand new 405m, first install of gamma OS 1.3.3 created issue of device resetting after screen timeout, the power button/device becomes unresponsive, soft reset needed to turn back on, stock os recovered yet problem continued even on "stock", reinstalled Gamma and problem continues. Have set time out to longest duration, this prolongs the reset/reboot cycling, and means you can use the power switch to put in sleep successfully as long as turned back on in the original 10 minutes time out window. Overall problem continues and is very frustrating

**Comment by L-K-M** [comment]
I have a very similar issue. I just installed 1.3.3 on a new RG505. When I put it to sleep by hitting the power button, after a while (it seems to be anywhere between 2 and 30 minutes, but I'm not entirely sure), it restarts on its own. It's fully charged.

**Comment by SlowPixel** [comment]
Yes, the problem is the same on 505. I noticed that this often happens when applications are open in the background and if they are not closed and put to sleep, a shutdown may occur.
Perhaps this coincides, but I have not yet identified the exact reason.
1.3.3 Last
And I put the wasps on a clean drain.
I really hope the new build will be more stable.

**Comment by Kyo-Tachibana** [comment]
> I can also confirm, brand new 405m, first install of gamma OS 1.3.3 created issue of device resetting after screen timeout, the power button/device becomes unresponsive, soft reset needed to turn back on, stock os recovered yet problem continued even on "stock", reinstalled Gamma and problem continues. Have set time out to longest duration, this prolongs the reset/reboot cycling, and means you can use the power switch to put in sleep successfully as long as turned back on in the original 10 minutes time out window. Overall problem continues and is very frustrating

I have the same problem, I installed the latest version full of gamma OS and when I press power to enter in sleep mode then turn off, or if it enter in standby turn it's turn off to...

**Comment by kkakele** [comment]
Does anybody found a fix for this? Everytime i push sleep button the rg505 crash and have to force restart.... Sorry for my english.Hope to find a solution soon....
