### ISSUE TITLE
RG405M re-mapping back/home to Retroarch Hotkey

### ISSUE THREAD

**Issue by alnjxn** [TheGammaSqueeze/GammaOS#57]
Hello

I setup my Hotkey as Select, but would like to go back to using the home/back button in Retroarch. This was listed as a feature since Retroarch asks to hold the button for 5 seconds, that just takes you back Home/Frontend. Maybe related I get an error about Virtual 0/0 not being mapped when pressing the Home key. 

Is there a way to revert back or set the Home/back to Hotkey after overriding?

**Comment by TheGammaSqueeze** [comment]
Hi, while setting the hotkey, hold down R1 and Home/Back, then let go of R1 while holding down Home/Back before the mapping is complete. That should map the hotkey back to home

**Comment by alnjxn** [comment]
Worked! Thank you 🙏
