### ISSUE TITLE
Stuck in the first launch

### ISSUE THREAD

**Issue by 6dean** [TheGammaSqueeze/GammaOS#59]
Hey,

I followed all steps from this video : https://www.youtube.com/watch?v=BD0ab1gr4gM
Now my RG405M doesn't start anymore, I am stuck from the first launch after using  EraseUserData : 

![IMG_5479 13100](https://github.com/TheGammaSqueeze/GammaOS/assets/114014511/0b212465-a3bb-46b2-8ddc-3c276f001217)

A brand new RG405M already dead lol

Thx

**Comment by inteyes** [comment]
Correct me if I'm wrong, but this video despite being very helpful, misses one important step - checking for another fastboot installations in the OS. I've already seen a couple of times on local forums that this is the culprit for the scripts not executing correctly.

Maybe it will be better to stick with the original instructions for this matter.
