### ISSUE TITLE
RetroArch Config Reset?

### ISSUE THREAD

**Issue by ph0bos** [TheGammaSqueeze/GammaOS#64]
The config in RetroArch has reset to defaults vs the GammaOS optimised version.

Symptoms of this reset:

- default RetroArch overlays display (loading banner,  touch controls)
- L/S + R/S hot key no longer brings up menu
- L/S does not work in some games (only d-pad is usable)

How do I make this happen?, how can it be avoided in future, and Is there a way to reset to the default Gamma OS settings please?

**Comment by TheGammaSqueeze** [comment]
Did you install any updates for RetroArch? Or install another version? I'm not sure how this could happen otherwise.

To reset it back to GammaOS defaults, you'll need to do a factory reset or do the following using ADB:

Use `adb root` on your pc, then do `adb shell`

Then run the following commands (make sure Retroarch is closed)

    /system/bin/tar -xvf /system/etc/retroarch64.tar.gz -C /data/tmpsetup/
    launcheruser=$( stat -c "%U" /data/data/com.retroarch.aarch64)
    launchergroup=$( stat -c "%G" /data/data/com.retroarch.aarch64)
    /system/bin/chown -R $launcheruser:$launchergroup /data/tmpsetup/data/data/com.retroarch.aarch64
    /system/bin/rm -rf /data/tmpsetup/data/data/com.retroarch.aarch64/cache
    /system/bin/rm -rf /data/tmpsetup/data/data/com.retroarch.aarch64/code_cache
    /system/bin/cp -pdrav /data/tmpsetup/data/data/com.retroarch.aarch64 /data/data/
    /system/bin/rm -rf /data/tmpsetup/*
    /system/bin/tar -xvf /system/etc/retroarch64sdcard.tar.gz -C /
    launcheruser=$( stat -c "%U" /data/data/com.retroarch.aarch64)
    /system/bin/chown -R $launcheruser:media_rw /sdcard/RetroArch
    /system/bin/tar -xvf /system/etc/retroarch64sdcard2.tar.gz -C /
    launcheruser=$( stat -c "%U" /data/data/com.retroarch.aarch64)
    /system/bin/chown -R $launcheruser:ext_data_rw /sdcard/Android/data/com.retroarch.aarch64
    /system/bin/pm grant com.retroarch.aarch64 android.permission.WRITE_EXTERNAL_STORAGE
    /system/bin/pm grant com.retroarch.aarch64 android.permission.READ_EXTERNAL_STORAGE
