### ISSUE TITLE
Feature request: AptX codec audio support

### ISSUE THREAD

**Issue by hoaxlayer** [TheGammaSqueeze/GammaOS#65]
For some reason, I am unable to select this audio codec in the developer options (only SBC and AAC seem to be supported)

The headphones I'm using DO support AptX (I tested this using a samsung smartphone, as well as a steam deck).

So my request is to add support for this codec.

If there's concern about licensing issues, I believe there is an open source reverse-engineered effort which could be used:
https://github.com/pali/libopenaptx

**Comment by freakazaa** [comment]
Read through issue #21. APTx support has been added starting from hotfix version 2. I personally used this version instead of the latter ones as I found it more stable. The latter version I tested (v4) tends to break the audio on some emulators such as RA and Mupen64PlusFZ.
