### ISSUE TITLE
SD Card Question

### ISSUE THREAD

**Issue by UrDone4** [TheGammaSqueeze/GammaOS#66]
Do I need to insert the SD card into the 405M and format it for GammaOS to recognize it? Or, will it recognize a fresh exFat formatted SD card without any steps needed?

Trying to determine if I can load up my SD with games while I wait for my 405M to be delivered, or if I need to wait and load them up after completing some steps on the device once I get GammaOS installed on it.  

Thanks for the help!

**Comment by TheGammaSqueeze** [comment]
It should recognise the card just fine without having to format in the 405m first.
When you insert it, if prompted just set up as portable storage.
