### ISSUE TITLE
Fixing bricked state: getting error “Failed: [PS2257]Uart send error” from spdflashtool

### ISSUE THREAD

**Issue by jsoryu** [TheGammaSqueeze/GammaOS#67]
Hello Gamma. First of all, thanks for creating this awesome firmware.

I’ve unfortunately had issues where device won’t turn on. In some occasions, go into boot loop.

Fact that spdflashtool detects the device, I assume it’s in bricked state and trying to reflash the original firmware.

I’ve been getting message “Failed: [PS2257] Uart send error” from spdflashtool and wondering what I can do to get this working.
- I’ve changed the USB cables to make sure they’re data compatible
- I’ve also tried to disconnect the battery and connect it back
- SD card is out

Any guidance is appreciated.

**Comment by TheGammaSqueeze** [comment]
You may need to hold down the home/back button, Power button and Vol down button to force it into a flashing state for the SPD tools to allow flashing.

I assume you have installed all the correct drivera and are on a Windows machine?

**Comment by jsoryu** [comment]
Answers are yes on all of those you’ve asked. Process begins after I’ve pressed the mentioned buttons (I’ve watched the YouTube video included in the instruction, as well as one recently mentioned in Anbernic discord.

I must’ve downloaded and tried virtually all variations of SPD tools; luckily they came with own drivers. (URL to download were included in all variations)

Regardless, Anbernic support just got back to me that they’ll send new board to me. Still, it’s a shame that I still can’t get past this.

I suppose we can close this ticket, but welcome on any suggestions and guidance.

Thanks

**Comment by nyckenn** [comment]
I have the same problem....have changed many cables and laptops but not working. Could you tell me the solution?

**Comment by RandomTurtle** [comment]
Same problem here :(

**Comment by Seriousattempts** [comment]
If your device cannot flash to the stock .pac file, assume your stuck.

I got the same issue with the Pocket 3 Plus (Also T618). Was able to flash to stock @nyckenn @RandomTurtle
