### ISSUE TITLE
SD Card Retention Issue

### ISSUE THREAD

**Issue by nabizzlesjj** [TheGammaSqueeze/GammaOS#68]
First of all, love the OS and thank you so much for your hard work. 

Wanted to report that after upgrading to GammaOS from stock, if I leave the RG405M in sleep for a good while and then wake it up from sleep, Android refuses to see any of the contents in my 1TB microsd card. I have to eject the card and reinsert the card to see it's contents. A restart will also show the contents on the card. 

I have confirmed that the card is good and not corrupted in any way. Would love to see if anyone else is experiencing this issue.

**Comment by TheGammaSqueeze** [comment]
I've not had any other reports around this, I am assuming this is resolved now due to how long ago this was raised.
