### ISSUE TITLE
Black Screen after formatting SDCARD in Settings

### ISSUE THREAD

**Issue by lmaule** [TheGammaSqueeze/GammaOS#69]
I formatted my Samsnung SD card from within the device settings and all went okay but whjen clicking the okay button the screen went blank. If you press a button or touch the screen it lights up for a second and then goes blank again.

Thew only way to fix it is to do a hard reset with Vol Up and Power button.

**Comment by TheGammaSqueeze** [comment]
I assume that this issue has been resolved.
