### ISSUE TITLE
Unable to flash vbmeta_a on RG505

### ISSUE THREAD

**Issue by geoffgs** [TheGammaSqueeze/GammaOS#71]
Started with a stock RG505 and trying to install Gamma 1.3.3

1. Worked around the Linux issue with unlocking the bootloader.
2. Started to flash from Ubuntu 22.04, but it failed at step 3 -- Easy to see why, RG505-FlashParitions.sh had a non-existent filename "fastboot flash boot_a flash/boot_custom.img_505  [...]". I'll PR this later. 
3. Switched to a Windows 11 host to unbrick, back to stock.
4. Tried again from Windows with the batch script, but flashing of vbmeta_a didn't complete even after 20 minutes
5. Unbricked back to stock again v1.23
6. Switched back to Linux, started with flashing vbmeta_a again manually, but again it doesn't complete after 30 minutes

`
fastboot flash vbmeta_a vbmeta_custom.img 
Sending 'vbmeta_a' (1024 KB)                       OKAY [  0.026s]
Writing 'vbmeta_a'    
`

From Linux I've been using fastboot 28.0.2 and from Windows the ADB & Fastboot++ as recommended. I had no issue with vbmeta_a the first time only from Linux, but failed every since so perhaps that was an issue with v1.23 of the stock firmware? Going to OTA to v1.24 and try again from Windows. -- Upgraded to 1.24 and still the same issue, vbmeta_a doesn't finish writing. No useful error messaging from fastboot either. 

I'm using the USB cable included from Anbernic, and it has no trouble with the debrick tool so I'm fairly confident it's fine. I've flashed Lineage plenty of times on a number of devices, and this is unusual to me. Any idea where I'm having trouble? Any help much appreciated.

**Comment by Ufoex** [comment]
I see that you closed it, I have the same problem as you, could you give me the solution you found?

**Comment by Ufoex** [comment]
I see that you closed it, I have the same problem as you, could you give me the solution you found?

**Comment by geoffgs** [comment]
> I see that you closed it, I have the same problem as you, could you give me the solution you found?

There was no perfect fix, but: 
1. Restore to stock with the Windows-only utility
2. Make sure you're in [fastbootd](https://source.android.com/docs/core/architecture/bootloader/fastbootd#adb-commands) before flashing: `adb reboot fastboot`
4. Repeat
