### ISSUE TITLE
Expand notification area width in landscape mode

### ISSUE THREAD

**Issue by d3adb5** [TheGammaSqueeze/GammaOS#79]
The RG405M (and I'm assuming the RG505 as well) screen is perpetually in landscape mode, likely by design as most Android games will default to operating in landscape. In the fourth beta version of Android 12, changes were made to the pull-down notification area when in landscape mode for the sake of more elongated aspect ratios: [notifications are now centered with huge margins on either side](https://www.androidheadlines.com/2021/08/android-12-odd-change-notifications-landscape.html) so that they're easier to read and reach.

Sadly when this applies to our dear RG405M, the margins don't scale down or get eliminated due to the screen's relatively low width in landscape mode, and so we get notifications that are rather crammed:

![image](https://github.com/TheGammaSqueeze/GammaOS/assets/8827351/f999e34f-177d-46e3-98ab-d22450baec92)

Due to apps preferring landscape mode over portrait, I feel like making Android recognize the different natural display orientation isn't the proper solution to this, but I have found no way to eliminate or lower those margins to an acceptable degree.

**Comment by PhucHauDeveloper** [comment]
> The RG405M (and I'm assuming the RG505 as well) screen is perpetually in landscape mode, likely by design as most Android games will default to operating in landscape. In the fourth beta version of Android 12, changes were made to the pull-down notification area when in landscape mode for the sake of more elongated aspect ratios: [notifications are now centered with huge margins on either side](https://www.androidheadlines.com/2021/08/android-12-odd-change-notifications-landscape.html) so that they're easier to read and reach.
> 
> Sadly when this applies to our dear RG405M, the margins don't scale down or get eliminated due to the screen's relatively low width in landscape mode, and so we get notifications that are rather crammed:
> 
> ![image](https://private-user-images.githubusercontent.com/8827351/269809396-f999e34f-177d-46e3-98ab-d22450baec92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjAwMTgsIm5iZiI6MTcwOTExOTcxOCwicGF0aCI6Ii84ODI3MzUxLzI2OTgwOTM5Ni1mOTk5ZTM0Zi0xNzdkLTQ2ZTMtOThhYi1kMjI0NTBiYWVjOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMTEyODM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjUxZGZkYmJlMWM3NzlmZWYxOGExODdlNTgyNzM4NjhmZjRiMjgwN2MzNzc2YzZjZTk5M2ZjZTRlNGJjMGYxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lfRzKLrGidv_Fu2HCS84FAi23yDaAk4m3Zel_npAPqY)
> 
> Due to apps preferring landscape mode over portrait, I feel like making Android recognize the different natural display orientation isn't the proper solution to this, but I have found no way to eliminate or lower those margins to an acceptable degree.

You can use the magisk module called "Better QS" version 1.0 by hani, which will help your QS panel no longer have excess space.

**Comment by d3adb5** [comment]
> You can use the magisk module called "Better QS" version 1.0 by hani, which will help your QS panel no longer have excess space.

The problem is with the notifications not spanning from one side of the screen to the other, not the quick settings panels. I haven't been able to find this Better QS module, though. Do you have a link?
