### ISSUE TITLE
Battery Issue on build 1.3.3

### ISSUE THREAD

**Issue by sumariana** [TheGammaSqueeze/GammaOS#87]
i was playing aetherSX2 for about 1.3hour the battery drain from 100 - 33 with performance mode turned on, is this normal? besides i was playing gba with pizza boy with power saving mode it draining from 30-18 with less than 30 minutes. how can i re-calibrate the battery ?

**Comment by TheGammaSqueeze** [comment]
Best way to recalibrate the battery is to disconnect it, reconnect then charge to 100% via your PC USB port (making sure the device is booted into Android, screen can be off). Then it should be fine after this.
