### ISSUE TITLE
Do we have an ETA for Gamma 405v release version?

### ISSUE THREAD

**Issue by wansadi** [TheGammaSqueeze/GammaOS#92]
I somehow flashed so called beta version in to my 405v. For the most part it works pretty good except for fan not working and no internet connection when connected to any wifi. Are we planning for a 405v version yet?

**Comment by rogiervanroon** [comment]
I'm also eager to see an update voor the 405V!

**Comment by thydungeonman** [comment]
I'd like to see this as well actually.

**Comment by SuperBadger77** [comment]
I'd love to see an official release too.

**Comment by TheGammaSqueeze** [comment]
Sadly the real life job keeps me very occupied at the moment. 
But the new release will be out in the next week or so.

**Comment by sammcj** [comment]
🤞 its out soon ready for Christmas gifting!

**Comment by rogiervanroon** [comment]
> 🤞 its out soon ready for Christmas gifting!

You sir, are awesome!

**Comment by Supermario1967** [comment]
Hi, I just received my Anbernic RG405V and want to use it with GammaOS from scratch . Is there a date when we can expect the ETA?

**Comment by Veddy74** [comment]
I flashed my 505 and it has been working great so on Christmas Eve I flashed my 405V, it worked fine until today when I just get the "G" logo turning at 90 degree angles over and over.  Do I need to "unbrick"?
