### ISSUE TITLE
Saturn games fail to load from Daijisho frontend

### ISSUE THREAD

**Issue by discus7l** [TheGammaSqueeze/GammaOS#94]
Using both the free and paid version of Yaba Sanshiro 2, the games fail to load from Daijisho. Let me know if any details are required.

**Comment by veb-xenon** [comment]
Same here. It just freezes...

**Comment by dfreivald** [comment]
It's known bug with Yaba Sanshiro. The YS dev has not updated the emulator for scoped storage, so later versions of android will not work with Daijisho.

Good news is Gamma has a workaround he wants to roll into the next update.

**Comment by discus7l** [comment]
Thanks for the heads up! Is it being discussed on a discord channel or something? I'd like to follow the discussion if possible.

**Comment by TheGammaSqueeze** [comment]
Yes this is fixed in the next GammaOS release. You can follow any discussions on the Retro Handhelds discord.
