### ISSUE TITLE
RG405m power saving mode not smooth for playing GBA - RetroArch 64 bit - VBA-M core

### ISSUE THREAD

**Issue by nuynait** [TheGammaSqueeze/GammaOS#96]
The game is not very smooth under power-saving mode. Switching to normal mode makes it run smoothly. Wanna ask if this is expected? 

https://github.com/TheGammaSqueeze/GammaOS/assets/2152195/350c298a-ea8c-45cf-8ee8-692941cbc737

I also tried SFC, same issue.

**Comment by nuynait** [comment]
Not sure if this is what we should expect for power saving mode or if its some of my configuration issue?

**Comment by TheGammaSqueeze** [comment]
M-gba requires more power. Use gpsp for power saving mode.
For SFC, use Snes9x EX+ standalone emulator.
For PSX, can use existing pcsx rearmed core, or use Duckstation standalone emulator.

**Comment by nuynait** [comment]
Thanks for the explanation.
