### ISSUE TITLE
Updating Magisk

### ISSUE THREAD

**Issue by andiweli** [TheGammaSqueeze/GammaOS#98]
How to update Magisk on GammaOS? It always brings up an error.

**Comment by Ace20xx** [comment]
I have the same issue with gamma os 1.5.1.
tried to update it but fail.

![20240227_125408](https://github.com/TheGammaSqueeze/GammaOS/assets/161413860/2261a8dd-05a5-448e-bde2-233521fe34d2)
![20240227_125417](https://github.com/TheGammaSqueeze/GammaOS/assets/161413860/c04ffc46-ee56-4162-bc1f-4fdfce1e0fb3)
![20240227_125424](https://github.com/TheGammaSqueeze/GammaOS/assets/161413860/ed892a56-7091-4ff1-9bde-bda0cb946de2)

**Comment by david-rosca** [comment]
I canc onfirm this is also an issue for me. I'm on the latest full GammaOS.
